#Build Stage
FROM mcr.microsoft.com/dotnet/sdk:3.1 AS builder
WORKDIR /src
COPY src/ .
USER ContainerAdministrator
RUN dotnet restore && dotnet publish

#final image stage
FROM mcr.microsoft.com/dotnet/sdk:3.1
WORKDIR /dotnetapp
COPY --from=builder /src/bin/Debug/netcoreapp3.1/publish .
CMD ["dotnet","My-App.dll"]