FROM python:3.7-alpine
WORKDIR /code
ENV FLASK=app-py
ENV FLASK_RUN_HOST=0.0.0.0
RUN apk add --no-cache gcc musl-dev linux-headers
COPY appdependencies.txt appdependencies.txt
RUN pip install -r appdependencies.txt
EXPOSE 6000
COPY . .
CMD ["flask","run"]

