# escape=`
#Choose an Image with IIS Enabled on Windows Server Core
FROM mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
#Set the default shell on the OS to PowerShell
SHELL ["PowerShell"]

ARG ENV_NAME=DEV

EXPOSE 80

COPY template.html C:\template.html

RUN (Get-Content -Raw -Path C:\template.html) `
    -replace '{hostname}', [Environment]::MachineName `
    -replace '{environment}', [Environment]::GetEnvironmentVariable('ENV_NAME') `
    | Set-Content -Path C:\inetpub\wwwroot\index.html
